all: philosophers holes

philosophers:philosophers.c
	gcc philosophers.c -o philosophers -Wall -ansi -std=c99 -pthread

holes:holes.c
	gcc holes.c -o holes -Wall -ansi -std=c99

clean:
	rm philosophers
